version: "3.9"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "5672:5672" # AMQP load balancing
            - "15672:15672" # Management UI load balancing
        volumes:
            - /mnt/d/OCodes/rabbitmq-cluster/nginx.conf:/etc/nginx/nginx.conf # Mount the NGINX config
        extra_hosts:
            - "rabbitmq-1:192.168.1.101" # Map hostnames to VM IPs
            - "rabbitmq-2:192.168.1.102"
            - "rabbitmq-3:192.168.1.103"
        networks:
            - nginx-net
        restart: unless-stopped

networks:
    nginx-net:
        driver: bridge
