version: "3.9"
services:
    rabbitmq-3:
        image: rabbitmq:3-management
        container_name: rabbitmq-3
        hostname: rabbitmq-3
        ports:
            - "4369:4369"
            - "5672:5672"
            - "15672:15672"
            - "25672:25672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_NODENAME: rabbit@192.168.1.103 # Replace with VM-3's IP
        command: >
            bash -c "sleep 20 && rabbitmqctl stop_app && rabbitmqctl join_cluster rabbit@192.168.1.101 && rabbitmqctl start_app"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_logs:/var/log/rabbitmq
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        networks:
            - rabbitmq_network

volumes:
    rabbitmq_data:
    rabbitmq_logs:


networks:
    rabbitmq_network:
        driver: bridge
