version: "3.9"
services:
    rabbitmq-1:
        image: rabbitmq:3-management
        container_name: rabbitmq-1
        hostname: rabbitmq-1 # Unique hostname for clustering
        ports:
            - "4369:4369" # EPMD port for clustering
            - "5672:5672" # AMQP port
            - "15672:15672" # Management UI
            - "25672:25672" # Cluster communication
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_NODENAME: rabbit@192.168.1.101 # Replace with VM-1's IP
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_logs:/var/log/rabbitmq
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        networks:
            - rabbitmq_network

volumes:
    rabbitmq_data:
    rabbitmq_logs:


networks:
    rabbitmq_network:
        driver: bridge
